Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2023-11, with the labels that each got.

#1029 docs: Add CLOB to Oracle BLOB validation document
  samples/oracle/README.md
Labels: size/S

#1031 fix: Adding credentials as parameter for Spanner
  third_party/ibis/ibis_cloud_spanner/__init__.py
  third_party/ibis/ibis_cloud_spanner/api.py
Labels: size/XS

#1026 feat: Support query parameter for MSSQL connection
  data_validation/cli_tools.py
  docs/connections.md
  third_party/ibis/ibis_mssql/__init__.py
  third_party/ibis/ibis_mssql/api.py
Labels: size/S

#1037 fix: Cast treats nullable and non-nullable columns in the same way
  third_party/ibis/ibis_addon/api.py
Labels: size/S

#1030 docs: Update connections.md to add supported version of DB2
  docs/connections.md
Labels: automerge, size/XS

#1042 fix: Fix decimal separator to "." (dot) on Oracle
  third_party/ibis/ibis_oracle/__init__.py
Labels: size/XS

#1034 fix: Adjust `find-tables` to properly get Oracle and Postgres schemas
  data_validation/__main__.py
  data_validation/clients.py
  third_party/ibis/ibis_postgres/client.py
Labels: size/S

#1024 test: integration test for Oracle to PostgreSQL
  ci/build.sh
  cloudbuild.yaml
  noxfile.py
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/test_oracle.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_oracle/datatypes.py
Labels: size/L

#1047 fix: --dry-run for SQLAlchemy clients with valid raw SQL
  data_validation/__main__.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_mysql.py
Labels: size/M

#1050 fix: Fix --grouped-columns issue for Oracle validation
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_oracle/compiler.py
Labels: size/XS

#1055 test: Limit Hive tests to single random Python version
  noxfile.py
Labels: size/XS

#1054 fix: Add Spanner RawSQL operation to enable filtering
  third_party/ibis/ibis_addon/operations.py
Labels: size/XS

#1062 fix: Spanner hash function returns string value instead of bytes
  tests/system/data_sources/test_spanner.py
  third_party/ibis/ibis_addon/operations.py
Labels: size/L
