Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2023-10, with the labels that each got.

#1014 fix: Solves Teradata `SSLMODE` support and adds support for additional `teradatasql` connection options as a JSON string
  data_validation/cli_tools.py
  docs/connections.md
  third_party/ibis/ibis_teradata/__init__.py
  third_party/ibis/ibis_teradata/api.py
Labels: size/S

#1019 chore: Builds are failing with a pip install cache error
  noxfile.py
Labels: size/XS

#1009 chore: Blacken 'third_party' files (lines, formatting) and add folder to noxfile.py
  noxfile.py
  tests/local_check.sh
  third_party/ibis/ibis_addon/api.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_cloud_spanner/__init__.py
  third_party/ibis/ibis_cloud_spanner/client.py
  third_party/ibis/ibis_cloud_spanner/compiler.py
  third_party/ibis/ibis_cloud_spanner/datatypes.py
  third_party/ibis/ibis_cloud_spanner/registry.py
  third_party/ibis/ibis_db2/__init__.py
  third_party/ibis/ibis_db2/api.py
  third_party/ibis/ibis_db2/compiler.py
  third_party/ibis/ibis_db2/datatypes.py
  third_party/ibis/ibis_db2/registry.py
  third_party/ibis/ibis_impala/api.py
  third_party/ibis/ibis_mysql/compiler.py
  third_party/ibis/ibis_oracle/__init__.py
  third_party/ibis/ibis_oracle/api.py
  third_party/ibis/ibis_oracle/datatypes.py
  third_party/ibis/ibis_oracle/registry.py
  third_party/ibis/ibis_postgres/client.py
  third_party/ibis/ibis_redshift/__init__.py
  third_party/ibis/ibis_redshift/api.py
  third_party/ibis/ibis_redshift/compiler.py
  third_party/ibis/ibis_snowflake/datatypes.py
  third_party/ibis/ibis_teradata/__init__.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/XL
