Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-07, with the labels that each got.

#1182 fix: Apply RTRIM on string column when generating partitions with `-tsp`
  data_validation/partition_builder.py
Labels: size/S

#1184 fix!: Failing validations of strings with extended ascii characters
  README.md
  data_validation/cli_tools.py
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/validation_builder.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_mysql.py
Labels: size/L

#1188 docs: Fix some typos in Cloud Run readme
  samples/cloud_run_jobs/README.md
Labels: size/S

#1178 feat: generate-table-partitions write multiple partitions to a single yaml file
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/partition_builder.py
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  tests/unit/test_partition_builder.py
Labels: size/XL

#1199 feat: Add TLS options to PostgreSQL connections add
  data_validation/cli_tools.py
  docs/connections.md
  third_party/ibis/ibis_postgres/client.py
Labels: size/M

#1197 fix: Close source and target connections after executing a validation
  data_validation/__main__.py
  data_validation/data_validation.py
  third_party/ibis/ibis_oracle/__init__.py
Labels: size/M

#1200 feat: Enhance PostgreSQL connections add documentation
  data_validation/cli_tools.py
  docs/connections.md
  third_party/ibis/ibis_postgres/client.py
Labels: size/M

#1203 fix: Support char comparison fields in Teradata
  data_validation/__main__.py
  data_validation/config_manager.py
  tests/system/data_sources/test_teradata.py
Labels: size/L

#1196 test: Add some more find-tables tests
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_sql_server.py
Labels: size/M

#1208 fix: Support DATE '0001-01-01' comparison fields
  third_party/ibis/ibis_addon/operations.py
Labels: size/XS

#1206 fix: More robust __exit__ on DataValidation()
  data_validation/config_manager.py
  data_validation/data_validation.py
Labels: size/S

#1204 fix: Oracle cast(decimal to string) caters for non-zero values <1
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_oracle/registry.py
Labels: size/M
