Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-02, with the labels that each got.

#1083 feat: Add --url to Oracle connections add options
  data_validation/cli_tools.py
  docs/connections.md
  noxfile.py
  tests/unit/test_cli_tools.py
Labels: size/L

#1085 tests: Fix unit tests when DB2 or Oracle dependencies are not present
  noxfile.py
  tests/unit/ibis_addon/__init__.py
  tests/unit/query_builder/__init__.py
  tests/unit/result_handlers/__init__.py
  third_party/ibis/ibis_addon/operations.py
Labels: size/M

#1087 docs: Add Airflow Kubernetes pod operator samples
  samples/airflow/kubernetes_pod_operator/DOCKERFILE
  samples/airflow/kubernetes_pod_operator/README.md
  samples/airflow/kubernetes_pod_operator/deploy.sh
  samples/airflow/kubernetes_pod_operator/kube_pod_op_dag.py
Labels: automerge, size/L

#1088 feat: set default oracle sql alchemy arraysize to 500
  third_party/ibis/ibis_oracle/__init__.py
Labels: automerge, size/XS

#1090 fix: Increase upper limit on number of columns that can be validated
  data_validation/combiner.py
Labels: size/S

#1100 fix: Pandas merge issue for Teradata empty result sets
  third_party/ibis/ibis_teradata/__init__.py
Labels: size/S

#1103 fix: case-insensitive comparison field support
  data_validation/config_manager.py
Labels: size/S
