Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-12, with the labels that each got.

#1359 chore: Add sample files using DVT for object reconcilliation
  samples/object_comparisons/README.md
  samples/object_comparisons/oracle/cons_fk.sql
  samples/object_comparisons/oracle/cons_nn.sql
  samples/object_comparisons/oracle/cons_pk.sql
  samples/object_comparisons/oracle/sequences.sql
  samples/object_comparisons/oracle/tables.sql
  samples/object_comparisons/oracle/triggers.sql
  samples/object_comparisons/oracle/views.sql
  samples/object_comparisons/postgres/cons_fk.sql
  samples/object_comparisons/postgres/cons_nn.sql
  samples/object_comparisons/postgres/cons_pk.sql
  samples/object_comparisons/postgres/sequences.sql
  samples/object_comparisons/postgres/tables.sql
  samples/object_comparisons/postgres/triggers.sql
  samples/object_comparisons/postgres/views.sql
  samples/object_comparisons/reconcile.sh
Labels: size/L

#1358 docs: Refine connection secret support section
  docs/connections.md
Labels: size/S

#1362 fix: Fix issue where long rows were being truncated in raw query command
  data_validation/__main__.py
  data_validation/raw_query.py
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_teradata.py
  tests/unit/test_raw_query.py
Labels: size/L

#1365 feat: Prevent column validation exceptions caused by Oracle CLOB JSON columns
  data_validation/config_manager.py
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/test_oracle.py
Labels: size/M

#1355 feat!: Exclude views from output of find tables
  data_validation/cli_tools.py
  data_validation/clients.py
  data_validation/find_tables.py
  tests/resources/bigquery_test_tables.sql
  tests/resources/hive_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  tests/unit/test_cli_tools.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_biquery/api.py
  third_party/ibis/ibis_cloud_spanner/__init__.py
  third_party/ibis/ibis_cloud_spanner/tests/ddl.sql
  third_party/ibis/ibis_impala/api.py
  third_party/ibis/ibis_teradata/__init__.py
Labels: size/L

#1373 docs: Update `docs/connections.md` and `samples/oracle/README.md`
  docs/connections.md
  samples/oracle/README.md
Labels: size/S
