Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-01, with the labels that each got.

#1058 feat: Support for Kubernetes
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  docs/internal/kubernetes_jobs.md
  tests/unit/test__main.py
Labels: size/L

#1076 feat: Add PostgreSQL OID support
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/test_postgres.py
  third_party/ibis/ibis_mssql/datatypes.py
  third_party/ibis/ibis_postgres/__init__.py
  third_party/ibis/ibis_postgres/datatypes.py
Labels: size/L

#1078 fix: Better casts to string for binary floats/doubles
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_oracle/registry.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/M

#1082 docs: updates on nested column limitations, contributing guide examples, and incorrect example
  CONTRIBUTING.md
  README.md
  docs/examples.md
Labels: size/S
