Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-11, with the labels that each got.

#1310 feat: user defined input `run_id` via config
  data_validation/cli_tools.py
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/data_validation.py
  data_validation/metadata.py
  tests/system/data_sources/test_bigquery.py
  tests/unit/test_cli_tools.py
  tests/unit/test_config_manager.py
  tests/unit/test_data_validation.py
Labels: size/L

#1316 fix: Hardcode SQLAlchemy max_identifier_length=128 for Oracle connections
  third_party/ibis/ibis_oracle/__init__.py
Labels: size/S

#1311 test: Update Cloud Build test sequencing
  cloudbuild.yaml
  noxfile.py
  tests/resources/mysql_test_tables.sql
Labels: size/S

#1323 fix: Fix --comp-fields bug losing option value before validation
  data_validation/__main__.py
  data_validation/config_manager.py
  tests/unit/test_config_manager.py
Labels: size/M

#1328 fix: Issue 1325
  data_validation/cli_tools.py
  data_validation/consts.py
Labels: size/S

#1307 docs: Add a sample script for VM automation of partitioning
  samples/bash/README.md
  samples/bash/auto_partition.sh
Labels: size/L

#1326 chore: Add instrumentation on query elapsed times
  data_validation/__main__.py
  data_validation/data_validation.py
  data_validation/util.py
  tests/unit/test_data_validation.py
  tests/unit/test_util.py
Labels: size/L

#1320 refactor: Optimize connection management to share connections
  data_validation/__main__.py
  data_validation/clients.py
  data_validation/data_validation.py
  third_party/ibis/ibis_db2/__init__.py
  third_party/ibis/ibis_mssql/__init__.py
  third_party/ibis/ibis_oracle/__init__.py
  third_party/ibis/ibis_postgres/client.py
  third_party/ibis/ibis_redshift/__init__.py
Labels: size/M

#1332 fix: catch InvalidArgument when checking if config vals are secrets
  data_validation/secret_manager.py
  tests/system/test_secret_manager.py
Labels: size/XS

#1329 chore: adding unit test coverage to `__main__.py`
  tests/unit/test__main.py
Labels: size/L

#1324 feat: Auto populate -pks when not provided by user
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/config_manager.py
  tests/resources/snowflake_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_db2.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  tests/unit/test_cli_tools.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_biquery/__init__.py
  third_party/ibis/ibis_biquery/api.py
  third_party/ibis/ibis_cloud_spanner/__init__.py
  third_party/ibis/ibis_db2/__init__.py
  third_party/ibis/ibis_impala/api.py
  third_party/ibis/ibis_mssql/__init__.py
  third_party/ibis/ibis_mysql/__init__.py
  third_party/ibis/ibis_oracle/__init__.py
  third_party/ibis/ibis_postgres/client.py
  third_party/ibis/ibis_redshift/__init__.py
  third_party/ibis/ibis_snowflake/datatypes.py
  third_party/ibis/ibis_teradata/__init__.py
Labels: size/L

#1346 tests: Check Oracle integration tests with Python 3.11
  noxfile.py
Labels: size/XS

#1352 chore: Create SECURITY.md
  SECURITY.md
Labels: automerge, size/XS

#1351 chore: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: automerge, size/M
