Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-03, with the labels that each got.

#1104 fix: Add table names to report results when source and/or target dataframes are empty
  data_validation/combiner.py
  data_validation/metadata.py
  tests/unit/test_combiner.py
Labels: size/M

#1110 fix: Fixes issue casting Snowflake decimal with scale>0 to string
  tests/resources/bigquery_test_tables.sql
  tests/resources/hive_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_sql_server.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_cloud_spanner/tests/dml.sql
Labels: size/M

#1114 fix: Numeric Overflow for Teradata COUNT column validation
  data_validation/query_builder/query_builder.py
Labels: size/XS

#1117 fix: Teradata large timestamp handling
  data_validation/combiner.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_teradata/__init__.py
Labels: size/M

#1121 fix: Teradata's ValueError after large timestamp epoch second handling
  third_party/ibis/ibis_addon/operations.py
Labels: size/S
