Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-09, with the labels that each got.

#1258 chore: bumping jellyfish version to 1.1.0
  setup.py
Labels: size/XS

#1257 docs: Add comments on both verbose and log-level parameters, also alter the…
  README.md
Labels: size/M

#1259 fix: Using datetime constants in filters
  data_validation/cli_tools.py
  docs/internal/filters_regex.md
  tests/unit/test_cli_tools.py
Labels: size/M

#1269 fix: Explicit set the parameter for line terminator on converting datafram…
  data_validation/result_handlers/text.py
Labels: automerge, size/XS

#1263 fix: big query run id message
  data_validation/result_handlers/bigquery.py
  tests/unit/test_data_validation.py
Labels: size/L

#1273 fix: Update Teradata rtrim() to account for tabs and other whitespace
  tests/resources/bigquery_test_tables.sql
  tests/resources/teradata_test_tables.sql
  third_party/ibis/ibis_teradata/registry.py
Labels: size/S

#1264 chore: bumping dependencies
  setup.py
Labels: size/M

#1265 feat: Enhance --tables-list to support schema.* shorthand for find-tables command
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/find_tables.py
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/unit/test__main.py
  tests/unit/test_find_tables.py
Labels: size/XL

#1245 fix: Oracle validations of tables with hyphen in name
  tests/resources/bigquery_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_oracle/__init__.py
Labels: size/XL

#1281 fix: cast count to bigint when generating partitions
  data_validation/query_builder/partition_row_builder.py
Labels: size/XS
