Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-10, with the labels that each got.

#1285 fix: Add proper handling for GCPSecretManager exceptions
  data_validation/secret_manager.py
  tests/local_check.sh
Labels: size/S

#1284 feat: Support row validation of boolean columns
  README.md
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/query_builder/query_builder.py
  tests/resources/bigquery_test_tables.sql
  tests/resources/hive_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/api.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_oracle/registry.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/XL

#1290 fix: Combiner did not take boolean datatypes into account
  data_validation/combiner.py
Labels: size/M

#1289 feat: Partition Custom Queries
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/config_manager.py
  data_validation/partition_builder.py
  data_validation/query_builder/partition_row_builder.py
  data_validation/validation_builder.py
  setup.py
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  tests/unit/test_cli_tools.py
  tests/unit/test_partition_builder.py
Labels: size/XL

#1291 feat: Add support for -comp-fields=*, which also adds support for --exclude-columns
  data_validation/__main__.py
  data_validation/config_manager.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
Labels: size/L

#1298 feat: Added ORC and PARQUET support among source tests
  cloudbuild.yaml
  data_validation/cli_tools.py
  data_validation/clients.py
  docs/connections.md
  noxfile.py
  tests/system/data_sources/test_filesystem.py
Labels: size/L

#1286 chore: Add integration tests for DB2 and missing changes for setup.py usage
  RELEASING.md
  ci/release_latest.sh
  cloudbuild.yaml
  noxfile.py
  samples/docker/build_docker.sh
  tests/local_check.sh
  tests/resources/db2_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_db2.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_db2/registry.py
Labels: size/XXL

#1304 fix: Correctly cater for Oracle FLOAT in custom-query validations
  tests/system/data_sources/test_oracle.py
  third_party/ibis/ibis_oracle/datatypes.py
  third_party/ibis/ibis_postgres/client.py
Labels: size/M
