Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-06, with the labels that each got.

#1156 chore: Add setup.py file back since release-please-bot requires it
  setup.py
Labels: size/M

#1155 feat: Support GCS custom query files
  README.md
  data_validation/config_manager.py
  data_validation/gcs_helper.py
  tests/system/test_state_manager.py
Labels: size/S

#1158 fix: Fixes bug in get_max_in_list_size
  data_validation/clients.py
  data_validation/validation_builder.py
  tests/unit/test_validation_builder.py
Labels: size/M

#1164 fix: Removing t0 alias from column name, while getting schema from query. Adding Integration test for Hive Custom-Query
  tests/system/data_sources/test_hive.py
  third_party/ibis/ibis_impala/api.py
Labels: size/S

#1166 feat: Support `--trim-string-pks` flag for padded string semantics
  README.md
  data_validation/cli_tools.py
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/data_validation.py
  data_validation/query_builder/query_builder.py
  data_validation/validation_builder.py
  tests/resources/bigquery_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_teradata.py
Labels: size/L

#1168 docs: Update generate-partitions flags
  README.md
  data_validation/cli_tools.py
Labels: size/L

#1172 test: Remove redundant test workaround
  tests/system/data_sources/test_snowflake.py
Labels: size/XS

#1173 test: Add unicode character tests
  tests/resources/bigquery_test_tables.sql
  tests/resources/hive_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
Labels: size/L

#1174 fix: Ensure BigQuery queries are executed in UTC
  data_validation/clients.py
Labels: size/S

#1176 docs: Tweaks to Cloud Functions sample
  samples/cloud_functions/README.md
  samples/cloud_functions/deploy.sh
  samples/cloud_functions/main.py
  samples/cloud_functions/requirements.txt
Labels: size/M
