Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-05, with the labels that each got.

#1113 fix: Fix casting from binary to string on Snowflake & BigQuery
  data_validation/config_manager.py
  tests/resources/bigquery_test_tables.sql
  tests/resources/db2_test_tables.sql
  tests/resources/hive_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_cloud_spanner/tests/ddl.sql
  third_party/ibis/ibis_cloud_spanner/tests/dml.sql
  third_party/ibis/ibis_db2/registry.py
  third_party/ibis/ibis_impala/api.py
  third_party/ibis/ibis_teradata/datatypes.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/XXL

#1126 fix!: Filters not working correctly in Snowflake
  README.md
  data_validation/query_builder/query_builder.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
Labels: size/M

#1129 feat!: Support for GCS config paths decoupled from environment variables
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/gcs_helper.py
  data_validation/partition_builder.py
  data_validation/secret_manager.py
  data_validation/state_manager.py
  docs/connections.md
  docs/internal/kubernetes_jobs.md
  noxfile.py
  samples/airflow/kubernetes_pod_operator/kube_pod_op_dag.py
  tests/system/data_sources/test_bigquery.py
  tests/system/test_state_manager.py
  tests/unit/test_cli_tools.py
  tests/unit/test_state_manager.py
Labels: size/XL

#1130 fix: Issue 1127 configs dir fails with more than 40 files
  data_validation/__main__.py
  tests/unit/test__main.py
Labels: size/S

#1135 feat: Add support for random row sampling on binary id columns
  data_validation/data_validation.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/L

#1138 feat: Control Teradata decimal format when cast to string
  third_party/ibis/ibis_teradata/registry.py
Labels: size/S

#1139 fix: Update to support up to 10K partitions
  data_validation/cli_tools.py
Labels: size/S

#1152 feat: Add a workaround for a Snowflake IN list limitation
  data_validation/query_builder/query_builder.py
  data_validation/validation_builder.py
  tests/unit/test_validation_builder.py
Labels: size/L

#1150 chore: Upgrade from setup.py to pyproject.toml
  RELEASING.md
  ci/release_latest.sh
  noxfile.py
  pyproject.toml
  samples/cloud_functions/requirements.txt
  samples/docker/build_docker.sh
  setup.py
  tests/local_check.sh
Labels: size/L
