Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2024-08, with the labels that each got.

#1215 fix: Oracle INTERVAL exception in validate schema
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/test_oracle.py
  third_party/ibis/ibis_oracle/datatypes.py
  third_party/ibis/ibis_oracle/registry.py
Labels: size/S

#1219 fix: Ensure Teradata OutofBound dates don't affect other date columns
  tests/local_check.sh
  third_party/ibis/ibis_teradata/__init__.py
Labels: size/S

#1220 fix: TD to BQ generate partitions with date PKs
  data_validation/config_manager.py
  data_validation/partition_builder.py
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_teradata.py
Labels: size/L

#1226 fix: TD to BQ - Support hash row validation with Latin and Unicode Characters in Strings
  tests/resources/bigquery_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
Labels: size/L

#1228 docs: Update Cloud Functions sample to support Cloud Scheduler job triggering
  samples/cloud_functions/main.py
Labels: automerge, size/XS

#1180 fix: Fixing multiple function call, to get schema in custom-query validation for Hive
  data_validation/config_manager.py
  third_party/ibis/ibis_impala/api.py
Labels: size/M

#1231 fix: Generate-partitions bug for date columns with different PK column casing
  data_validation/partition_builder.py
Labels: size/S

#1229 feat: Time data type support - some additional fixes for timezone aware types
  tests/resources/bigquery_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_mssql/registry.py
  third_party/ibis/ibis_teradata/datatypes.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/L

#1230 fix: Adds automatic RTRIM for custom query row validations for Teradata string comparison fields
  data_validation/__main__.py
Labels: size/S

#1235 chore: Remove redundant code from build_config_calculated_fields()
  data_validation/config_manager.py
Labels: size/S

#1238 feat: Add Oracle TIMESTAMP WITH LOCAL TIME ZONE support
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  third_party/ibis/ibis_oracle/datatypes.py
Labels: size/S

#1240 feat: BigQuery result handler logs textual output at DEBUG instead of INFO
  data_validation/config_manager.py
  data_validation/result_handlers/bigquery.py
  data_validation/result_handlers/text.py
Labels: size/M

#1243 feat: Adding exclude_columns flag for row validation hash
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/config_manager.py
  tests/unit/test_config_manager.py
Labels: size/L

#1246 fix: Set `RAND()` as default for DB2's random function
  third_party/ibis/ibis_db2/registry.py
Labels: size/XS
