Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2025-01, with the labels that each got.

#1384 feat: Prevent exceptions due to PostgreSQL xml data type
  tests/resources/postgresql_test_tables.sql
  third_party/ibis/ibis_postgres/datatypes.py
Labels: size/S

#1387 fix: Cast of Oracle Timestamp to Date removes the time component
  tests/resources/bigquery_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  third_party/ibis/ibis_oracle/registry.py
Labels: size/L

#1402 docs: Add Snowflake key-pair example
  docs/connections.md
Labels: size/XS

#1398 feat: add connections cli commands
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/gcs_helper.py
  data_validation/state_manager.py
  docs/connections.md
  tests/unit/test__main.py
  tests/unit/test_cli_tools.py
  tests/unit/test_state_manager.py
Labels: size/L

#1404 docs: Add sample of horizontally scaled Oracle BLOB validation
  samples/oracle/README.md
  samples/oracle/lob_validations.md
  samples/oracle/scaling_lob_validations.md
Labels: size/L

#1397 feat: Cater for ExtractEpochSeconds overflowing integer
  tests/resources/bigquery_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_mssql/registry.py
  third_party/ibis/ibis_postgres/registry.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/L

#1392 fix: Workaround for dates < 1970 on Windows
  tests/unit/ibis_addon/test_operations.py
  third_party/ibis/ibis_addon/operations.py
Labels: size/M

#1409 chore: Remove CODEOWNERS
  CODEOWNERS
Labels: size/S

#1407 fix: Cast epoch_seconds to int64 in combiner
  data_validation/combiner.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
Labels: size/M

#1412 fix: Cast sum of epoch_seconds to string to avoid int64 overflow
  data_validation/config_manager.py
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_postgres.py
  third_party/ibis/ibis_oracle/registry.py
Labels: size/M
