Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2025-02, with the labels that each got.

#1418 fix: Change get_filters to not hang due to long filter strings
  data_validation/cli_tools.py
  data_validation/util.py
  noxfile.py
  setup.py
  tests/unit/test_cli_tools.py
  tests/unit/test_util.py
Labels: size/L

#1415 fix: Row validations fail for values with trailing newline
  tests/resources/bigquery_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_addon/operations.py
  third_party/ibis/ibis_cloud_spanner/tests/ddl.sql
  third_party/ibis/ibis_cloud_spanner/tests/dml.sql
Labels: size/XXL

#1431 fix: Convert Snowflake connect_args to a dict before passing to Ibis
  data_validation/util.py
  tests/unit/test_cli_tools.py
  tests/unit/test_util.py
  third_party/ibis/ibis_snowflake/api.py
  third_party/ibis/ibis_teradata/__init__.py
  third_party/ibis/ibis_teradata/api.py
Labels: size/L

#1437 fix: Prevent exception for COLUMN keyword in Oracle
  tests/resources/bigquery_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_oracle/__init__.py
Labels: size/XL

#1417 feat: Print summary information after row validation
  data_validation/__main__.py
  data_validation/combiner.py
  data_validation/consts.py
  data_validation/data_validation.py
  data_validation/result_handlers/bigquery.py
  tests/unit/test_combiner.py
Labels: size/L

#1441 fix: Add PermissionDenied to ignorable exceptions in maybe_secret()
  data_validation/secret_manager.py
Labels: size/XS
