Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2025-03, with the labels that each got.

#1413 chore: Add initial templates for new issues and pull requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: size/L

#1458 fix: PostgreSQL epoch_seconds expression now matches Oracle/BigQuery/SQL Server/etc
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  third_party/ibis/ibis_postgres/registry.py
Labels: size/S

#1452 fix: Include Int64 in data types to cast to string during sum column validation
  data_validation/config_manager.py
  tests/resources/postgresql_test_tables.sql
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_oracle.py
Labels: size/M

#1450 feat: Add --format option to raw query command
  README.md
  data_validation/__main__.py
  data_validation/cli_tools.py
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/partition_builder.py
  data_validation/raw_query.py
  data_validation/result_handlers/bigquery.py
  data_validation/result_handlers/text.py
  docs/examples.md
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_filesystem.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_spanner.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  tests/unit/result_handlers/test_text.py
  tests/unit/test__main.py
  tests/unit/test_cli_tools.py
  tests/unit/test_data_validation.py
  tests/unit/test_partition_builder.py
  tests/unit/test_raw_query.py
  tests/unit/test_schema_validation.py
Labels: size/L

#1456 test: Enable tests incorrectly left disabled
  tests/system/data_sources/test_oracle.py
Labels: size/M

#1461 fix: Prevent logging an exception when result_df is empty
  data_validation/combiner.py
  tests/unit/test_combiner.py
Labels: size/M

#1469 feat: Add raw_column_metadata to Oracle, Teradata and PostgreSQL Backend objects
  data_validation/config_manager.py
  noxfile.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_teradata.py
  tests/unit/ibis_oracle/__init__.py
  tests/unit/ibis_oracle/test_init.py
  tests/unit/ibis_postgres/__init__.py
  tests/unit/ibis_postgres/test_init.py
  tests/unit/ibis_teradata/__init__.py
  tests/unit/ibis_teradata/test_init.py
  tests/unit/test_clients.py
  third_party/ibis/ibis_oracle/__init__.py
  third_party/ibis/ibis_postgres/client.py
  third_party/ibis/ibis_teradata/__init__.py
Labels: size/XL

#1465 fix: Prevent RecursionError in combiner by slicing Dataframes by validation count
  data_validation/combiner.py
  data_validation/config_manager.py
  data_validation/consts.py
  data_validation/data_validation.py
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/unit/test_combiner.py
  tests/unit/test_config_manager.py
Labels: size/L

#1475 fix: Cater for extreme datetime pk values
  data_validation/partition_builder.py
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
Labels: size/L

#1478 test: Remove fixed version from pyfakefs
  CONTRIBUTING.md
  noxfile.py
  setup.py
  tests/local_check.sh
Labels: size/XS

#1481 fix: Reduced VARCHAR length when casting Teradata integrals to string
  setup.py
  tests/resources/oracle_test_tables.sql
  tests/resources/teradata_test_tables.sql
  third_party/ibis/ibis_teradata/registry.py
Labels: size/S

#1485 test: Cater for Spanner config via env vars in integration test module
  tests/system/data_sources/test_spanner.py
Labels: size/XS
