Repository GoogleCloudPlatform/professional-services-data-validator, pull requests merged in 2025-04, with the labels that each got.

#1490 fix: Cater for OID > 2 billion in PostgreSQL _metadata method
  third_party/ibis/ibis_postgres/client.py
Labels: size/XS

#1496 fix: Ensure --partition-num option is > 1
  data_validation/cli_tools.py
  tests/unit/test_cli_tools.py
Labels: size/M

#1495 feat: Optimize PostgreSQL result handler
  data_validation/result_handlers/base_backend.py
  data_validation/result_handlers/bigquery.py
  data_validation/result_handlers/postgres.py
  data_validation/result_handlers/text.py
  docs/connections.md
  docs/internal/result_handlers.md
  tests/resources/bigquery_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/test_postgres.py
Labels: size/L

#1499 fix: Issue casting SQL Server DECIMAL with scale > 0 to string
  tests/system/data_sources/test_sql_server.py
  tests/unit/test_combiner.py
  third_party/ibis/ibis_addon/operations.py
Labels: size/M

#1500 fix: Issue 1497 generate partitions custom query
  data_validation/__main__.py
  data_validation/config_manager.py
  data_validation/partition_builder.py
  data_validation/util.py
  tests/resources/bigquery_test_tables.sql
  tests/resources/hive_test_tables.sql
  tests/resources/impala_test_tables.sql
  tests/resources/mysql_test_tables.sql
  tests/resources/oracle_test_tables.sql
  tests/resources/postgresql_test_tables.sql
  tests/resources/snowflake_test_tables.sql
  tests/resources/sqlserver_test_tables.sql
  tests/resources/teradata_test_tables.sql
  tests/system/data_sources/common_functions.py
  tests/system/data_sources/deploy_cloudsql/gcloud_context.py
  tests/system/data_sources/test_bigquery.py
  tests/system/data_sources/test_hive.py
  tests/system/data_sources/test_impala.py
  tests/system/data_sources/test_mysql.py
  tests/system/data_sources/test_oracle.py
  tests/system/data_sources/test_postgres.py
  tests/system/data_sources/test_snowflake.py
  tests/system/data_sources/test_sql_server.py
  tests/system/data_sources/test_teradata.py
  tests/unit/test_partition_builder.py
Labels: size/XXL

#1506 fix: Support Teradata filters containing quotes when generating partitions
  tests/system/data_sources/test_teradata.py
  third_party/ibis/ibis_teradata/registry.py
Labels: size/M

#1509 chore: Replace literals with constants and rename the literals to less risky values
  data_validation/combiner.py
  data_validation/consts.py
Labels: size/S
